#include <stdio.h>
#include "export.h"

void print_html_top_part(void) {
  printf("<!DOCTYPE html>\n"
         "<html lang=\"en\">\n"
         "<head>\n"
         " <meta charset=\"UTF-8\">\n"
         " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
         " <title>Pomodoros</title>\n"
         " <style>\n"
         "  body {\n"
         "   font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
         "   line-height: 1.6;\n"
         "   max-width: 900px;\n"
         "   margin: 0 auto;\n"
         "   padding: 20px;\n"
         "   background-color: #f8f9fa;\n"
         "   color: #333;\n"
         "  }\n\n"
         "  h1 {\n"
         "   text-align: center\n"
         "   color: #d63031;\n"
         "   padding-bottom: 15px; \n"
         "   border-bottom: 2px solid #dfe6e9;\n"
         "   margin-bottom: 30px;\n"
         "  }\n\n"
         "  div {\n"
         "   background-color: white;\n"
         "   border-radius: 8px; \n"
         "   padding: 20px;\n"
         "   margin-bottom: 25px;\n"
         "   box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);\n"
         "   border: 1px solid #e9ecef;\n"
         "  }\n\n"
         "  h2 {\n"
         "   color: #2d3436;\n"
         "   background-color: #fff5f5;\n"
         "   padding: 12px 15px;\n"
         "   border-radius: 6px;\n"
         "   margin: -20px -20px 20px -20px;\n"
         "   border-left: 4px solid #d63031;\n"
         "   font-size: 1.2rem;\n"
         "  }\n\n"
         "  table {\n"
         "   width: 100%%;\n"
         "   border-collapse: collapse;\n"
         "  }\n\n"
         "  th {\n"
         "   background-color: #f8f9fa; \n"
         "   text-align: left; \n"
         "   padding: 12px 15px; \n"
         "   border-bottom: 2px solid #dfe6e9; \n"
         "   color: #495057; \n"
         "   font-weight: 600; \n"
         "  }\n\n"
         "  td {\n"
         "   padding: 12px 15px; \n"
         "   border-bottom: 1px solid #e9ecef;\n"
         "  }\n\n"
         "  tr:hover {\n"
         "   background-color: #f8f9fa;\n"
         "  }\n\n"
         "  tr:last-child td {\n"
         "   border-bottom: none;\n"
         "  }\n\n"
         "  .subject {\n"
         "   font-weight: 500;\n"
         "   color: #2d3436;\n"
         "  }\n\n"
         "  .tomato {\n"
         "    color: #d63031;\n"
         "    font-size: 1.1rem;\n"
         "    letter-spacing: 2px;\n"
         "  }\n\n"
         "  .time {\n"
         "    font-weight: 500;\n"
         "    color: #0984e3;\n"
         "  }\n\n"
         " </style>\n"
         "</head>\n"
         "<body>\n"
         " <h1>Pomodoros</h1>\n"
         );
}

void print_table_top_part(const char* date, char* pomodoro_duration) {
  printf(" <div>\n"
         "  <h2>%s - 🍅 = %s</h2>\n"
         "   <table>\n"
         "    <tr>\n"
         "     <th>Subject</th>\n"
         "     <th>Ammount</th>\n"
         "     <th>Time</th>\n"
         "    </tr>\n",
         date,
         pomodoro_duration
         );
}

void print_table_down_part(void) {
  printf("   </table>\n"
         " </div>\n");
}
 
void print_html_down_part(void) {
  printf("</body>\n"
         "</html>\n");
}
